#pragma once

namespace smartview
{
	// After 'No Parsing', these are in alphabetical order
	static SMARTVIEW_PARSER_TYPE_ARRAY_ENTRY g_SmartViewParserTypeArray[] = {
		{parserType::IDS_STNOPARSING, L"Choose Smart View Parser"}, // STRING_OK
		{parserType::IDS_STADDITIONALRENENTRYIDSEX, L"Additional Ren Entry IDs Ex"}, // STRING_OK
		{parserType::IDS_STAPPOINTMENTRECURRENCEPATTERN, L"Appointment Recurrence Pattern"}, // STRING_OK
		{parserType::IDS_STCONVERSATIONINDEX, L"Conversation Index"}, // STRING_OK
		{parserType::IDS_STENTRYID, L"Entry Id"}, // STRING_OK
		{parserType::IDS_STENTRYLIST, L"Entry List"}, // STRING_OK
		{parserType::IDS_STEXTENDEDFOLDERFLAGS, L"Extended Folder Flags"}, // STRING_OK
		{parserType::IDS_STEXTENDEDRULECONDITION, L"Extended Rule Condition"}, // STRING_OK
		{parserType::IDS_STFLATENTRYLIST, L"Flat Entry List"}, // STRING_OK
		{parserType::IDS_STFOLDERUSERFIELDS, L"Folder User Fields Stream"}, // STRING_OK
		{parserType::IDS_STGLOBALOBJECTID, L"Global Object Id"}, // STRING_OK
		{parserType::IDS_STPROPERTIES, L"Property"}, // STRING_OK
		{parserType::IDS_STPROPERTYDEFINITIONSTREAM, L"Property Definition Stream"}, // STRING_OK
		{parserType::IDS_STRECIPIENTROWSTREAM, L"Recipient Row Stream"}, // STRING_OK
		{parserType::IDS_STRECURRENCEPATTERN, L"Recurrence Pattern"}, // STRING_OK
		{parserType::IDS_STREPORTTAG, L"Report Tag"}, // STRING_OK
		{parserType::IDS_STRESTRICTION, L"Restriction"}, // STRING_OK
		{parserType::IDS_STRULECONDITION, L"Rule Condition"}, // STRING_OK
		{parserType::IDS_STSEARCHFOLDERDEFINITION, L"Search Folder Definition"}, // STRING_OK
		{parserType::IDS_STSECURITYDESCRIPTOR, L"Security Descriptor"}, // STRING_OK
		{parserType::IDS_STSID, L"SID"}, // STRING_OK
		{parserType::IDS_STTASKASSIGNERS, L"Task Assigners"}, // STRING_OK
		{parserType::IDS_STTIMEZONE, L"Time Zone"}, // STRING_OK
		{parserType::IDS_STTIMEZONEDEFINITION, L"Time Zone Definition"}, // STRING_OK
		{parserType::IDS_STWEBVIEWPERSISTSTREAM, L"Web View Persistence Object Stream"}, // STRING_OK
		{parserType::IDS_STNICKNAMECACHE, L"Nickname Cache"}, // STRING_OK
		{parserType::IDS_STENCODEENTRYID, L"Encode Entry ID"}, // STRING_OK
		{parserType::IDS_STDECODEENTRYID, L"Decode Entry ID"}, // STRING_OK
		{parserType::IDS_STVERBSTREAM, L"Verb Stream"}, // STRING_OK
		{parserType::IDS_STTOMBSTONE, L"Tombstone"}, // STRING_OK
		{parserType::IDS_STPCL, L"Predecessor Change List"}, // STRING_OK
		{parserType::IDS_STFBSECURITYDESCRIPTOR, L"Free Busy Security Descriptor"}, // STRING_OK
		{parserType::IDS_STXID, L"XID"}, // STRING_OK
	};

	static SMARTVIEW_PARSER_ARRAY_ENTRY g_SmartViewParserArray[] = {
		// clang-format off
		BINARY_STRUCTURE_ENTRY(PR_REPORT_TAG, parserType::IDS_STREPORTTAG)
		BINARY_STRUCTURE_ENTRY(PR_RECEIVED_BY_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_SENT_REPRESENTING_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_RCVD_REPRESENTING_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_REPORT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_READ_RECEIPT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ORIGINAL_AUTHOR_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_REPLY_RECIPIENT_ENTRIES, parserType::IDS_STFLATENTRYLIST)
		BINARY_STRUCTURE_ENTRY(PR_ORIGINAL_SENDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ORIGINAL_SENT_REPRESENTING_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_CONVERSATION_INDEX, parserType::IDS_STCONVERSATIONINDEX)
		BINARY_STRUCTURE_ENTRY(PR_SENDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_PARENT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_SENTMAIL_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_NT_SECURITY_DESCRIPTOR, parserType::IDS_STSECURITYDESCRIPTOR)
		BINARY_STRUCTURE_ENTRY(PR_CREATOR_SID, parserType::IDS_STSID)
		BINARY_STRUCTURE_ENTRY(PR_LAST_MODIFIER_SID, parserType::IDS_STSID)
		BINARY_STRUCTURE_ENTRY(PR_EXTENDED_RULE_MSG_CONDITION, parserType::IDS_STEXTENDEDRULECONDITION)
		BINARY_STRUCTURE_ENTRY(PR_FREEBUSY_NT_SECURITY_DESCRIPTOR, parserType::IDS_STFBSECURITYDESCRIPTOR)
		BINARY_STRUCTURE_ENTRY(PR_STORE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ORIGINALLY_INTENDED_RECIP_ENTRYID, parserType::IDS_STENTRYID)
		MV_BINARY_STRUCTURE_ENTRY(PR_CONFLICT_ITEMS, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_TARGET_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_SUBTREE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_OUTBOX_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_WASTEBASKET_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_SENTMAIL_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_VIEWS_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_COMMON_VIEWS_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_FINDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_DEFAULT_VIEW_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_APPOINTMENT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_CONTACT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_JOURNAL_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_NOTE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_TASK_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_REM_ONLINE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_REM_OFFLINE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_DRAFTS_ENTRYID, parserType::IDS_STENTRYID)
		MV_BINARY_STRUCTURE_ENTRY(PR_ADDITIONAL_REN_ENTRYIDS, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ADDITIONAL_REN_ENTRYIDS_EX, parserType::IDS_STADDITIONALRENENTRYIDSEX)
		BINARY_STRUCTURE_ENTRY(PR_EXTENDED_FOLDER_FLAGS, parserType::IDS_STEXTENDEDFOLDERFLAGS)
		BINARY_STRUCTURE_ENTRY(PR_FOLDER_WEBVIEWINFO, parserType::IDS_STWEBVIEWPERSISTSTREAM)
		BINARY_STRUCTURE_ENTRY(PR_USERFIELDS, parserType::IDS_STFOLDERUSERFIELDS)
		MV_BINARY_STRUCTURE_ENTRY(PR_FREEBUSY_ENTRYIDS, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ALTERNATE_RECIPIENT, parserType::IDS_STFLATENTRYLIST)
		BINARY_STRUCTURE_ENTRY(PR_ORIGINAL_ENTRYID, parserType::IDS_STENTRYID)
		MV_BINARY_STRUCTURE_ENTRY(PR_AB_SEARCH_PATH, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IDENTITY_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_OWN_STORE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_HEADER_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_CONFLICT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_MOVE_TO_STORE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_MOVE_TO_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_CREATOR_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_LAST_MODIFIER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_RECIPIENT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_USER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_MAILBOX_OWNER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_SCHEDULE_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_DAF_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_NON_IPM_SUBTREE_ENTRYID, parserType::IDS_STENTRYID)
		MV_BINARY_STRUCTURE_ENTRY(PR_CONTAB_FOLDER_ENTRYIDS, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_EFORMS_REGISTRY_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_SPLUS_FREE_BUSY_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_OFFLINE_ADDRBOOK_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_EFORMS_FOR_LOCALE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_FREE_BUSY_FOR_LOCAL_SITE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ADDRBOOK_FOR_LOCAL_SITE_ENTRYID, parserType::IDS_STENTRYID)
		MV_BINARY_STRUCTURE_ENTRY(PR_CONTAB_STORE_ENTRYIDS, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_OFFLINE_MESSAGE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_GW_MTSIN_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_GW_MTSOUT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_FAVORITES_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_IPM_PUBLIC_FOLDERS_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_SYS_CONFIG_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ADDRESS_BOOK_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_PUBLIC_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_DAM_ORIGINAL_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_RULE_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ACTIVE_USER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_ORIGINATOR_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_REPORT_DESTINATION_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_LONGTERM_ENTRYID_FROM_TABLE, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_EVENTS_ROOT_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_NNTP_ARTICLE_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_NEWSGROUP_ROOT_FOLDER_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_WLINK_AB_EXSTOREEID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_WLINK_ABEID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_WLINK_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_WLINK_STORE_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_WB_SF_DEFINITION, parserType::IDS_STSEARCHFOLDERDEFINITION)
		MV_BINARY_STRUCTURE_ENTRY(PR_SCHDINFO_DELEGATE_ENTRYIDS, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_EMS_AB_PARENT_ENTRYID, parserType::IDS_STENTRYID)
		BINARY_STRUCTURE_ENTRY(PR_SCHDINFO_APPT_TOMBSTONE, parserType::IDS_STTOMBSTONE)
		BINARY_STRUCTURE_ENTRY(PR_PREDECESSOR_CHANGE_LIST, parserType::IDS_STPCL)
		BINARY_STRUCTURE_ENTRY(PR_CHANGE_KEY, parserType::IDS_STXID)

		NAMEDPROP_BINARY_STRUCTURE_ENTRY(LID_GLOBAL_OBJID, PSETID_Meeting, parserType::IDS_STGLOBALOBJECTID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(LID_CLEAN_GLOBAL_OBJID, PSETID_Meeting, parserType::IDS_STGLOBALOBJECTID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSelectedOriginalEntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidAnniversaryEventEID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_MV_BINARY_STRUCTURE_ENTRY(dispidDLOneOffMembers, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_MV_BINARY_STRUCTURE_ENTRY(dispidDLMembers, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidEmail1OriginalEntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidEmail2OriginalEntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidEmail3OriginalEntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidFax1EntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidFax2EntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidFax3EntryID, PSETID_Address, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidTaskRecur, PSETID_Task, parserType::IDS_STRECURRENCEPATTERN)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidTaskMyDelegators, PSETID_Task, parserType::IDS_STTASKASSIGNERS)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidApptRecur, PSETID_Appointment, parserType::IDS_STAPPOINTMENTRECURRENCEPATTERN)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidTimeZoneStruct, PSETID_Appointment, parserType::IDS_STTIMEZONE)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidOrigStoreEid, PSETID_Appointment, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidApptUnsendableRecips, PSETID_Appointment, parserType::IDS_STRECIPIENTROWSTREAM)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidApptTZDefStartDisplay, PSETID_Appointment, parserType::IDS_STTIMEZONEDEFINITION)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidApptTZDefEndDisplay, PSETID_Appointment, parserType::IDS_STTIMEZONEDEFINITION)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidApptTZDefRecur, PSETID_Appointment, parserType::IDS_STTIMEZONEDEFINITION)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidForwardNotificationRecipients, PSETID_Appointment, parserType::IDS_STRECIPIENTROWSTREAM)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidPropDefStream, PSETID_Common, parserType::IDS_STPROPERTYDEFINITIONSTREAM)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidContactLinkEntry, PSETID_Common, parserType::IDS_STFLATENTRYLIST)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidReferenceEID, PSETID_Common, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSharingInitiatorEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSharingFolderEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSharingOriginalMessageEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSharingBindingEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSharingIndexEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidSharingParentBindingEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidConvActionMoveFolderEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidConvActionMoveStoreEid, PSETID_Sharing, parserType::IDS_STENTRYID)
		NAMEDPROP_BINARY_STRUCTURE_ENTRY(dispidVerbStream, PSETID_Common, parserType::IDS_STVERBSTREAM)

		BINARY_STRUCTURE_ENTRY(PR_RULE_ID, parserType::IDS_STPTI8)
		BINARY_STRUCTURE_ENTRY(PidTagFolderId, parserType::IDS_STSFIDMID)
		BINARY_STRUCTURE_ENTRY(PidTagMid, parserType::IDS_STSFIDMID)
		BINARY_STRUCTURE_ENTRY(PR_WB_SF_LAST_USED, parserType::IDS_STLONGRTIME)
		BINARY_STRUCTURE_ENTRY(PR_WB_SF_EXPIRATION, parserType::IDS_STLONGRTIME)
		BINARY_STRUCTURE_ENTRY(PR_FREEBUSY_PUBLISH_START, parserType::IDS_STLONGRTIME)
		BINARY_STRUCTURE_ENTRY(PR_FREEBUSY_PUBLISH_END, parserType::IDS_STLONGRTIME)
		// clang-format on
	};
} // namespace smartview