#pragma once

#define GUID_ENTRY(guid) {&(guid),L#guid},

GUID_ARRAY_ENTRY g_PropGuidArray[] =
{
	GUID_ENTRY(PS_MAPI)
	GUID_ENTRY(PS_PUBLIC_STRINGS)
	GUID_ENTRY(PS_ROUTING_EMAIL_ADDRESSES)
	GUID_ENTRY(PS_ROUTING_ADDRTYPE)
	GUID_ENTRY(PS_ROUTING_DISPLAY_NAME)
	GUID_ENTRY(PS_ROUTING_ENTRYID)
	GUID_ENTRY(PS_ROUTING_SEARCH_KEY)
	GUID_ENTRY(PS_INTERNET_HEADERS)
	GUID_ENTRY(IID_IMessageRaw)
	GUID_ENTRY(PSETID_Appointment)
	GUID_ENTRY(PSETID_Task)
	GUID_ENTRY(PSETID_Address)
	GUID_ENTRY(PSETID_Common)
	GUID_ENTRY(PSETID_Log)
	GUID_ENTRY(IID_IProxyStoreObject)
	GUID_ENTRY(GUID_Dilkie)
	GUID_ENTRY(PSETID_Meeting)
	GUID_ENTRY(IID_IAttachmentSecurity)
};
