#include "stdafx.h"
#include "PropTagArray.h"

#include "guids.h"
// this file is the autogenerated array of property tags, sorted by value
#include "GenTagArray.h"
#include "Flags.h"
#include "GuidArray.h"
#include "NameIDArray.h"
#include "PropTypeArray.h"

ULONG g_ulPropTagArray = _countof(g_PropTagArray);
ULONG g_ulFlagArray = _countof(g_FlagArray);
ULONG g_ulPropGuidArray = _countof(g_PropGuidArray);
ULONG g_ulNameIDArray = _countof(g_NameIDArray);
ULONG g_ulPropTypeArray = _countof(g_PropTypeArray);
