#include "stdafx.h"
#include "PropTagArray.h"

#include "guids.h"
// this file is the autogenerated array of property tags, sorted by value
#include "GenTagArray.h"
#include "Flags.h"
#include "GuidArray.h"
#include "NameIDArray.h"
#include "PropTypeArray.h"

ULONG g_ulPropTagArray = sizeof(g_PropTagArray)/sizeof(NAME_ARRAY_ENTRY);
ULONG g_ulFlagArray = sizeof(g_FlagArray)/sizeof(FLAG_ARRAY_ENTRY);
ULONG g_ulPropGuidArray = sizeof(g_PropGuidArray)/sizeof(GUID_ARRAY_ENTRY);
ULONG g_ulNameIDArray = sizeof(g_NameIDArray)/sizeof(NAMEID_ARRAY_ENTRY);
ULONG g_ulPropTypeArray = sizeof(g_PropTypeArray)/sizeof(NAME_ARRAY_ENTRY);
