binskim.exe analyze C:\src\mfcmapi\MFCMapi.exe
binskim.exe analyze C:\src\mfcmapi\bin\Win32\MrMAPI\Release\MrMAPI.exe
binskim.exe analyze C:\src\mfcmapi\bin\Win32\MrMAPI\Release_Unicode\MrMAPI.exe
binskim.exe analyze C:\src\mfcmapi\bin\Win32\Release\MFCMapi.exe
binskim.exe analyze C:\src\mfcmapi\bin\Win32\Release_Unicode\MFCMapi.exe
binskim.exe analyze C:\src\mfcmapi\bin\Win32\exampleMapiConsoleApp\Release\exampleMapiConsoleApp.exe
binskim.exe analyze C:\src\mfcmapi\bin\Win32\exampleMapiConsoleApp\Release_Unicode\exampleMapiConsoleApp.exe
binskim.exe analyze C:\src\mfcmapi\bin\x64\MrMAPI\Release\MrMAPI.exe
binskim.exe analyze C:\src\mfcmapi\bin\x64\MrMAPI\Release_Unicode\MrMAPI.exe
binskim.exe analyze C:\src\mfcmapi\bin\x64\Release\MFCMapi.exe
binskim.exe analyze C:\src\mfcmapi\bin\x64\Release_Unicode\MFCMapi.exe
binskim.exe analyze C:\src\mfcmapi\bin\x64\exampleMapiConsoleApp\Release\exampleMapiConsoleApp.exe
binskim.exe analyze C:\src\mfcmapi\bin\x64\exampleMapiConsoleApp\Release_Unicode\exampleMapiConsoleApp.exe