# Common build script
parameters:
- name: name
  type: string
- name: platform
  type: string
- name: configuration
  type: string

jobs:
- job: ${{ parameters.name }}
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - powershell: |
      gci env:BUILD_BUILDNUMBER
      $Env:BUILD_BUILDNUMBER -match "(\d+)\.(\d+)\.(\d+)\.(\d+)"
      $m = $matches
      $file = gci "$Env:BUILD_SOURCESDIRECTORY\core\res\bldver.rc"
      if($file)
      {
      attrib $file -r
      $fc = Get-Content($file)
      $fc = $fc -replace "#define rmj (\d+)", ("#define rmj "+$m[1])
      $fc = $fc -replace "#define rmm (\d+)", ("#define rmm "+$m[2])
      $fc = $fc -replace "#define rup (\d+)", ("#define rup "+$m[3])
      $fc = $fc -replace "#define rmn (\d+)", ("#define rmn "+$m[4])
      $fc | Out-File $file
      }
    displayName: 'Add Version'

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: '**/*.sln'
      vsVersion: latest
      msbuildArgs: '/p:SourceLinkCreate=true'
      platform: ${{ parameters.platform }}
      configuration: ${{ parameters.configuration }}
      clean: true
      maximumCpuCount: true
      msbuildArchitecture: x64
      createLogFile: true

  - task: VSTest@2
    displayName: 'VsTest - UnitTests'
    inputs:
      runInParallel: true
      codeCoverageEnabled: true
      diagnosticsEnabled: True

  # This might consume azure artifact space which is super limited
  # We'll keep symbols over in the github release instead
  # - task: PublishSymbols@2
  #   displayName: 'Publish symbols path'
  #   inputs:
  #     IndexSources: false
  #     SymbolServerType: TeamServices
  #     DetailedLog: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: artifactstagingdirectory'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\bin'
      Contents: |
        **\mfcmapi.exe
        **\mfcmapi.pdb
        **\mrmapi.exe
        **\mrmapi.pdb
      TargetFolder: '$(build.artifactstagingdirectory)'
      CleanTargetFolder: true
      OverWrite: true

  # setting this up requres some sort of auth token - figure it out later
  # - task: APIScan@2
  #   displayName: Run APIScan
  #   continueOnError: true
  #   inputs:
  #     softwareFolder: '$(Build.StagingDirectory)'
  #     softwareBuildNum: '$(Build.BuildId)'
  #     symbolsFolder: '$(Build.StagingDirectory)'
  #     softwareName: 'MFCMAPI'
  #     softwareVersionNum: '$(Build.BuildNumber)'

  - task: AntiMalware@4
    displayName: Run AntiMalware
    continueOnError: true
    inputs:
      InputType: 'Basic'
      ScanType: 'CustomScan'
      FileDirPath: '$(build.artifactstagingdirectory)'
      TreatSignatureUpdateFailureAs: 'Warning'
      SignatureFreshness: 'UpToDate'
      TreatStaleSignatureAs: 'Error'

  - task: BinSkim@4
    displayName: Run BinSkim
    continueOnError: true
    inputs:
      InputType: 'Basic'
      Function: 'analyze'
      TargetPattern: 'guardianGlob'
      AnalyzeTargetGlob: '$(Build.ArtifactStagingDirectory)/**.dll;$(Build.ArtifactStagingDirectory)/**.exe;'

  - task: CodeInspector@2
    displayName: 'Run Code Inspector'
    continueOnError: true
    inputs:
      ProductId: 0

  - task: ComponentGovernanceComponentDetection@0
    displayName: Run Component Governance Component Detection
    continueOnError: true
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

  - task: CredScan@3
    displayName: Run CredScan
    continueOnError: true
    inputs:
      outputFormat: pre
      verboseOutput: true
      debugMode: false
      folderSuppression: false

  - task: PoliCheck@2
    displayName: Run PoliCheck
    continueOnError: true
    inputs:
      targetType: F
      result: PoliCheck.xml

  - task: SDLNativeRules@3
    displayName: 'Run the PREfast SDL Native Rules for MSBuild'
    inputs:
      publishXML: false
      userProvideBuildInfo: auto
      # excludedPaths: 'path/to/exclude'
      rulesetName: Recommended
    env:
      system_accesstoken: $(System.AccessToken)

  # This takes far too long to run - disable for now
  # - task: Semmle@1
  #   displayName: Run Semmle
  #   continueOnError: true
  #   inputs:
  #     sourceCodeDirectory: '$(Build.SourcesDirectory)'
  #     language: 'cpp'
  #     querySuite: 'Recommended'
  #     timeout: '1800'
  #     ram: '16384'
  #     addProjectDirToScanningExclusionList: true

  - task: SdtReport@2
    displayName: Create Security Analysis Report
    continueOnError: true
    inputs:
      GdnExportTsvFile: true
      GdnExportHtmlFile: true
      GdnExportOutputBaselineFile: myBaseline
      GdnExportOutputBaseline: myBaselinedResults
      GdnExportOutputSuppressionFile: mySuppressions
      GdnExportOutputSuppressionSet: mySuppressionSet
      GdnExportPolicyMinSev: Warning
      # GdnExportGdnToolApiScanSeverity: Warning
      GdnExportGdnToolArmorySeverity: Warning
      GdnExportGdnToolBinSkimSeverity: Warning
      # GdnExportGdnToolCodesignValidationSeverity: Warning
      GdnExportGdnToolCredScanSeverity: Warning
      GdnExportGdnToolPoliCheckSeverity: Warning
      GdnExportGdnToolSDLNativeRulesSeverity: Warning
      # GdnExportGdnToolSemmleSeverity: Warning

  - task: PublishSecurityAnalysisLogs@3
    displayName: Publish Security Analysis Logs
    inputs:
      ArtifactName: CodeAnalysisLogs

  - task: PostAnalysis@2
    displayName: Post Analysis
    inputs:
      GdnBreakSuppressionSets: default
      GdnBreakPolicyMinSev: Warning
 
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'Generation Task'
    inputs:
      BuildDropPath: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'