#include <UnitTest/stdafx.h>
#include <UnitTest/UnitTest.h>
#include <core/smartview/SmartView.h>
#include <core/addin/mfcmapi.h>
#include <core/addin/addin.h>
#include <core/utility/strings.h>

namespace SmartViewTest
{
	TEST_CLASS(SmartViewTest)
	{
	private:
		struct SmartViewTestResource
		{
			parserType structType{};
			DWORD hex{};
			DWORD expected{};
		};

		struct SmartViewTestData
		{
			parserType structType{};
			bool parseAll{};
			std::wstring testName;
			std::vector<BYTE> hex;
			std::wstring expected;
		};

		void test(const std::initializer_list<SmartViewTestResource>& resources) const
		{
			auto testData = loadTestData(resources);
			for (auto& data : testData)
			{
				auto actual = smartview::InterpretBinaryAsString(
					{static_cast<ULONG>(data.hex.size()), data.hex.data()}, data.structType, nullptr);
				unittest::AreEqualEx(data.expected, actual, data.testName.c_str());

				if (unittest::parse_all)
				{
					for (auto parser : SmartViewParserTypeArray)
					{
						const auto structType = parser.type;
						try
						{
							actual = smartview::InterpretBinaryAsString(
								{static_cast<ULONG>(data.hex.size()), data.hex.data()}, structType, nullptr);
						} catch (const int exception)
						{
							Logger::WriteMessage(strings::format(
													 L"Testing %ws failed at %ws with error 0x%08X\n",
													 data.testName.c_str(),
													 addin::AddInStructTypeToString(structType).c_str(),
													 exception)
													 .c_str());
							Assert::Fail();
						}
					}
				}
			}
		}

		static std::vector<SmartViewTestData> loadTestData(
			const std::initializer_list<SmartViewTestResource>& resources)
		{
			static auto handle = GetModuleHandleW(L"UnitTest.dll");
			std::vector<SmartViewTestData> testData;
			for (const auto& resource : resources)
			{
				// See comments on loadfile for best file encoding strategies for test data
				testData.push_back(SmartViewTestData{resource.structType,
													 unittest::parse_all,
													 strings::format(L"%d/%d", resource.hex, resource.expected),
													 strings::HexStringToBin(unittest::loadfile(handle, resource.hex)),
													 unittest::loadfile(handle, resource.expected)});
			}

			return testData;
		}

	public:
		TEST_CLASS_INITIALIZE(initialize) { unittest::init(); }

		TEST_METHOD(Test_STADDITIONALRENENTRYIDSEX)
		{
			test({
				{parserType::ADDITIONALRENENTRYIDSEX, IDR_SV1AEI1IN, IDR_SV1AEI1OUT},
				{parserType::ADDITIONALRENENTRYIDSEX, IDR_SV1AEI2IN, IDR_SV1AEI2OUT},
				{parserType::ADDITIONALRENENTRYIDSEX, IDR_SV1AEI3IN, IDR_SV1AEI3OUT},
				{parserType::ADDITIONALRENENTRYIDSEX, IDR_SV1AEI4IN, IDR_SV1AEI4OUT},
			});
		}

		TEST_METHOD(Test_STAPPOINTMENTRECURRENCEPATTERN)
		{
			test({
				{parserType::APPOINTMENTRECURRENCEPATTERN, IDR_SV2ARP1IN, IDR_SV2ARP1OUT},
				{parserType::APPOINTMENTRECURRENCEPATTERN, IDR_SV2ARP2IN, IDR_SV2ARP2OUT},
				{parserType::APPOINTMENTRECURRENCEPATTERN, IDR_SV2ARP3IN, IDR_SV2ARP3OUT},
				{parserType::APPOINTMENTRECURRENCEPATTERN, IDR_SV2ARP4IN, IDR_SV2ARP4OUT},
			});
		}

		TEST_METHOD(Test_STCONVERSATIONINDEX)
		{
			test({
				{parserType::CONVERSATIONINDEX, IDR_SV3CI1IN, IDR_SV3CI1OUT},
				{parserType::CONVERSATIONINDEX, IDR_SV3CI2IN, IDR_SV3CI2OUT},
				{parserType::CONVERSATIONINDEX, IDR_SV3CI3IN, IDR_SV3CI3OUT},
				{parserType::CONVERSATIONINDEX, IDR_SV3CI4IN, IDR_SV3CI4OUT},
			});
		}

		TEST_METHOD(Test_STENTRYID)
		{
			test({
				{parserType::ENTRYID, IDR_SV4EID1IN, IDR_SV4EID1OUT},
				{parserType::ENTRYID, IDR_SV4EID2IN, IDR_SV4EID2OUT},
				{parserType::ENTRYID, IDR_SV4EID3IN, IDR_SV4EID3OUT},
				{parserType::ENTRYID, IDR_SV4EID4IN, IDR_SV4EID4OUT},
				{parserType::ENTRYID, IDR_SV4EID5IN, IDR_SV4EID5OUT},
				{parserType::ENTRYID, IDR_SV4EID6IN, IDR_SV4EID6OUT},
				{parserType::ENTRYID, IDR_SV4EID7IN, IDR_SV4EID7OUT},
				{parserType::ENTRYID, IDR_SV4EID8IN, IDR_SV4EID8OUT},
				{parserType::ENTRYID, IDR_SV4EID9IN, IDR_SV4EID9OUT},
				{parserType::ENTRYID, IDR_SV4EID10IN, IDR_SV4EID10OUT},
				{parserType::ENTRYID, IDR_SV4EID11IN, IDR_SV4EID11OUT},
				{parserType::ENTRYID, IDR_SV4EID12IN, IDR_SV4EID12OUT},
				{parserType::ENTRYID, IDR_SV4EID13IN, IDR_SV4EID13OUT},
				{parserType::ENTRYID, IDR_SV4EID14IN, IDR_SV4EID14OUT},
				{parserType::ENTRYID, IDR_SV4EID15IN, IDR_SV4EID15OUT},
				{parserType::ENTRYID, IDR_SV4EID16IN, IDR_SV4EID16OUT},
				{parserType::ENTRYID, IDR_SV4EID17IN, IDR_SV4EID17OUT},
				{parserType::ENTRYID, IDR_SV4EID18IN, IDR_SV4EID18OUT},
				{parserType::ENTRYID, IDR_SV4EID19IN, IDR_SV4EID19OUT},
				{parserType::ENTRYID, IDR_SV4EID20IN, IDR_SV4EID20OUT},
				{parserType::ENTRYID, IDR_SV4EID21IN, IDR_SV4EID21OUT},
				{parserType::ENTRYID, IDR_SV4EID22IN, IDR_SV4EID22OUT},
				{parserType::ENTRYID, IDR_SV4EID23IN, IDR_SV4EID23OUT},
				{parserType::ENTRYID, IDR_SV4EID24IN, IDR_SV4EID24OUT},
				{parserType::ENTRYID, IDR_SV4EID25IN, IDR_SV4EID25OUT},
				{parserType::ENTRYID, IDR_SV4EID26IN, IDR_SV4EID26OUT},
				{parserType::ENTRYID, IDR_SV4EID27IN, IDR_SV4EID27OUT},
				{parserType::ENTRYID, IDR_SV4EID28IN, IDR_SV4EID28OUT},
				{parserType::ENTRYID, IDR_SV4EID29IN, IDR_SV4EID29OUT},
				{parserType::ENTRYID, IDR_SV4EID30IN, IDR_SV4EID30OUT},
				{parserType::ENTRYID, IDR_SV4EID31IN, IDR_SV4EID31OUT},
				{parserType::ENTRYID, IDR_SV4EID32IN, IDR_SV4EID32OUT},
				{parserType::ENTRYID, IDR_SV4EID33IN, IDR_SV4EID33OUT},
				{parserType::ENTRYID, IDR_SV4EID34IN, IDR_SV4EID34OUT},
				{parserType::ENTRYID, IDR_SV4EID35IN, IDR_SV4EID35OUT},
				{parserType::ENTRYID, IDR_SV4EID36IN, IDR_SV4EID36OUT},
				{parserType::ENTRYID, IDR_SV4EID37IN, IDR_SV4EID37OUT},
				{parserType::ENTRYID, IDR_SV4EID38IN, IDR_SV4EID38OUT},
				{parserType::ENTRYID, IDR_SV4EID39IN, IDR_SV4EID39OUT},
				{parserType::ENTRYID, IDR_SV4EID40IN, IDR_SV4EID40OUT},
			});
		}

		TEST_METHOD(Test_STENTRYLIST)
		{
			test({
				{parserType::ENTRYLIST, IDR_SV5EL1IN, IDR_SV5EL1OUT},
				{parserType::ENTRYLIST, IDR_SV5EL2IN, IDR_SV5EL2OUT},
			});
		}

		TEST_METHOD(Test_STEXTENDEDFOLDERFLAGS)
		{
			test({
				{parserType::EXTENDEDFOLDERFLAGS, IDR_SV6EFF1IN, IDR_SV6EFF1OUT},
				{parserType::EXTENDEDFOLDERFLAGS, IDR_SV6EFF2IN, IDR_SV6EFF2OUT},
			});
		}

		TEST_METHOD(Test_STEXTENDEDRULECONDITION)
		{
			test({
				{parserType::EXTENDEDRULECONDITION, IDR_SV7EXRULE1IN, IDR_SV7EXRULE1OUT},
				{parserType::EXTENDEDRULECONDITION, IDR_SV7EXRULE2IN, IDR_SV7EXRULE2OUT},
				{parserType::EXTENDEDRULECONDITION, IDR_SV7EXRULE3IN, IDR_SV7EXRULE3OUT},
				{parserType::EXTENDEDRULECONDITION, IDR_SV7EXRULE4IN, IDR_SV7EXRULE4OUT},
			});
		}

		TEST_METHOD(Test_STFLATENTRYLIST)
		{
			test({
				{parserType::FLATENTRYLIST, IDR_SV8FE1IN, IDR_SV8FE1OUT},
				{parserType::FLATENTRYLIST, IDR_SV8FE2IN, IDR_SV8FE2OUT},
				{parserType::FLATENTRYLIST, IDR_SV8FE3IN, IDR_SV8FE3OUT},
			});
		}

		TEST_METHOD(Test_STFOLDERUSERFIELDS)
		{
			test({
				{parserType::FOLDERUSERFIELDS, IDR_SV9FUF1IN, IDR_SV9FUF1OUT},
				{parserType::FOLDERUSERFIELDS, IDR_SV9FUF2IN, IDR_SV9FUF2OUT},
				{parserType::FOLDERUSERFIELDS, IDR_SV9FUF3IN, IDR_SV9FUF3OUT},
				{parserType::FOLDERUSERFIELDS, IDR_SV9FUF4IN, IDR_SV9FUF4OUT},
				{parserType::FOLDERUSERFIELDS, IDR_SV9FUF5IN, IDR_SV9FUF5OUT},
			});
		}

		TEST_METHOD(Test_STGLOBALOBJECTID)
		{
			test({
				{parserType::GLOBALOBJECTID, IDR_SV10GOID1IN, IDR_SV10GOID1OUT},
				{parserType::GLOBALOBJECTID, IDR_SV10GOID2IN, IDR_SV10GOID2OUT},
			});
		}

		TEST_METHOD(Test_STPROPERTY)
		{
			test({
				{parserType::PROPERTIES, IDR_SV11PROP1IN, IDR_SV11PROP1OUT},
				{parserType::PROPERTIES, IDR_SV11PROP2IN, IDR_SV11PROP2OUT},
				{parserType::PROPERTIES, IDR_SV11PROP3IN, IDR_SV11PROP3OUT},
				{parserType::PROPERTIES, IDR_SV11PROP4IN, IDR_SV11PROP4OUT},
				{parserType::PROPERTIES, IDR_SV11PROP5IN, IDR_SV11PROP5OUT},
				{parserType::PROPERTIES, IDR_SV11PROP6IN, IDR_SV11PROP6OUT},
				{parserType::PROPERTIES, IDR_SV11PROP7IN, IDR_SV11PROP7OUT},
				{parserType::PROPERTIES, IDR_SV11PROP8IN, IDR_SV11PROP8OUT},
			});
		}

		TEST_METHOD(Test_STPROPERTYDEFINITIONSTREAM)
		{
			test({
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF1IN, IDR_SV12PROPDEF1OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF2IN, IDR_SV12PROPDEF2OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF3IN, IDR_SV12PROPDEF3OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF4IN, IDR_SV12PROPDEF4OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF5IN, IDR_SV12PROPDEF5OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF6IN, IDR_SV12PROPDEF6OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF7IN, IDR_SV12PROPDEF7OUT},
				{parserType::PROPERTYDEFINITIONSTREAM, IDR_SV12PROPDEF8IN, IDR_SV12PROPDEF8OUT},
			});
		}

		TEST_METHOD(Test_STRECIPIENTROWSTREAM)
		{
			test({
				{parserType::RECIPIENTROWSTREAM, IDR_SV13RECIPROW1IN, IDR_SV13RECIPROW1OUT},
				{parserType::RECIPIENTROWSTREAM, IDR_SV13RECIPROW2IN, IDR_SV13RECIPROW2OUT},
			});
		}

		TEST_METHOD(Test_STRECURRENCEPATTERN)
		{
			test({
				{parserType::RECURRENCEPATTERN, IDR_SV14ARP1IN, IDR_SV14ARP1OUT},
				{parserType::RECURRENCEPATTERN, IDR_SV14ARP2IN, IDR_SV14ARP2OUT},
				{parserType::RECURRENCEPATTERN, IDR_SV14ARP3IN, IDR_SV14ARP3OUT},
			});
		}

		TEST_METHOD(Test_STREPORTTAG)
		{
			test({
				{parserType::REPORTTAG, IDR_SV15REPORTTAG1IN, IDR_SV15REPORTTAG1OUT},
			});
		}

		TEST_METHOD(Test_STRESTRICTION)
		{
			test({
				{parserType::RESTRICTION, IDR_SV16RES1IN, IDR_SV16RES1OUT},
				{parserType::RESTRICTION, IDR_SV16RES2IN, IDR_SV16RES2OUT},
				{parserType::RESTRICTION, IDR_SV16RES3IN, IDR_SV16RES3OUT},
				{parserType::RESTRICTION, IDR_SV16RES4IN, IDR_SV16RES4OUT},
			});
		}

		TEST_METHOD(Test_STRULECONDITION)
		{
			test({
				{parserType::RULECONDITION, IDR_SV17RULECON1IN, IDR_SV17RULECON1OUT},
				{parserType::RULECONDITION, IDR_SV17RULECON2IN, IDR_SV17RULECON2OUT},
				{parserType::RULECONDITION, IDR_SV17RULECON3IN, IDR_SV17RULECON3OUT},
				{parserType::RULECONDITION, IDR_SV17RULECON4IN, IDR_SV17RULECON4OUT},
			});
		}

		TEST_METHOD(Test_STSEARCHFOLDERDEFINITION)
		{
			test({
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF1IN, IDR_SV18SF1OUT},
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF2IN, IDR_SV18SF2OUT},
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF3IN, IDR_SV18SF3OUT},
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF4IN, IDR_SV18SF4OUT},
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF5IN, IDR_SV18SF5OUT},
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF6IN, IDR_SV18SF6OUT},
				{parserType::SEARCHFOLDERDEFINITION, IDR_SV18SF7IN, IDR_SV18SF7OUT},
			});
		}

		TEST_METHOD(Test_STSECURITYDESCRIPTOR)
		{
			test({
				{parserType::SECURITYDESCRIPTOR, IDR_SV19SD1IN, IDR_SV19SD1OUT},
				{parserType::SECURITYDESCRIPTOR, IDR_SV19SD2IN, IDR_SV19SD2OUT},
				{parserType::SECURITYDESCRIPTOR, IDR_SV19SD3IN, IDR_SV19SD3OUT},
				{parserType::SECURITYDESCRIPTOR, IDR_SV19SD4IN, IDR_SV19SD4OUT},
			});
		}

		TEST_METHOD(Test_STSID)
		{
			test({
				{parserType::SID, IDR_SV20SID1IN, IDR_SV20SID1OUT},
				{parserType::SID, IDR_SV20SID2IN, IDR_SV20SID2OUT},
				{parserType::SID, IDR_SV20SID3IN, IDR_SV20SID3OUT},
				{parserType::SID, IDR_SV20SID4IN, IDR_SV20SID4OUT},
				{parserType::SID, IDR_SV20SID5IN, IDR_SV20SID5OUT},
			});
		}

		TEST_METHOD(Test_STTASKASSIGNERS)
		{
			test({
				{parserType::TASKASSIGNERS, IDR_SV21TA1IN, IDR_SV21TA1OUT},
			});
		}

		TEST_METHOD(Test_STTIMEZONE)
		{
			test({
				{parserType::TIMEZONE, IDR_SV22TZ1IN, IDR_SV22TZ1OUT},
			});
		}

		TEST_METHOD(Test_STTIMEZONEDEFINITION)
		{
			test({
				{parserType::TIMEZONEDEFINITION, IDR_SV23TZD1IN, IDR_SV23TZD1OUT},
				{parserType::TIMEZONEDEFINITION, IDR_SV23TZD2IN, IDR_SV23TZD2OUT},
				{parserType::TIMEZONEDEFINITION, IDR_SV23TZD3IN, IDR_SV23TZD3OUT},
			});
		}

		TEST_METHOD(Test_STWEBVIEWPERSISTSTREAM)
		{
			test({
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW1IN, IDR_SV24WEBVIEW1OUT},
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW2IN, IDR_SV24WEBVIEW2OUT},
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW3IN, IDR_SV24WEBVIEW3OUT},
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW4IN, IDR_SV24WEBVIEW4OUT},
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW5IN, IDR_SV24WEBVIEW5OUT},
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW6IN, IDR_SV24WEBVIEW6OUT},
				{parserType::WEBVIEWPERSISTSTREAM, IDR_SV24WEBVIEW7IN, IDR_SV24WEBVIEW7OUT},
			});
		}

		TEST_METHOD(Test_STNICKNAMECACHE)
		{
			test({
				{parserType::NICKNAMECACHE, IDR_SV25NICKNAME2IN, IDR_SV25NICKNAME2OUT},
				{parserType::NICKNAMECACHE, IDR_SV25NICKNAME3IN, IDR_SV25NICKNAME3OUT},
				{parserType::NICKNAMECACHE, IDR_SV25NICKNAME4IN, IDR_SV25NICKNAME4OUT},
			});
		}

		TEST_METHOD(Test_STENCODEENTRYID)
		{
			test({
				{parserType::ENCODEENTRYID, IDR_SV26EIDENCODE1IN, IDR_SV26EIDENCODE1OUT},
			});
		}

		TEST_METHOD(Test_STDECODEENTRYID)
		{
			test({
				{parserType::DECODEENTRYID, IDR_SV27EIDDECODE1IN, IDR_SV27EIDDECODE1OUT},
			});
		}

		TEST_METHOD(Test_STVERBSTREAM)
		{
			test({
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM1IN, IDR_SV28VERBSTREAM1OUT},
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM2IN, IDR_SV28VERBSTREAM2OUT},
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM3IN, IDR_SV28VERBSTREAM3OUT},
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM4IN, IDR_SV28VERBSTREAM4OUT},
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM5IN, IDR_SV28VERBSTREAM5OUT},
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM6IN, IDR_SV28VERBSTREAM6OUT},
				{parserType::VERBSTREAM, IDR_SV28VERBSTREAM7IN, IDR_SV28VERBSTREAM7OUT},
			});
		}

		TEST_METHOD(Test_STTOMBSTONE)
		{
			test({
				{parserType::TOMBSTONE, IDR_SV29TOMBSTONE1IN, IDR_SV29TOMBSTONE1OUT},
				{parserType::TOMBSTONE, IDR_SV29TOMBSTONE2IN, IDR_SV29TOMBSTONE2OUT},
				{parserType::TOMBSTONE, IDR_SV29TOMBSTONE3IN, IDR_SV29TOMBSTONE3OUT},
			});
		}

		TEST_METHOD(Test_STPCL)
		{
			test({
				{parserType::PCL, IDR_SV30PCL1IN, IDR_SV30PCL1OUT},
				{parserType::PCL, IDR_SV30PCL2IN, IDR_SV30PCL2OUT},
				{parserType::PCL, IDR_SV30PCL3IN, IDR_SV30PCL3OUT},
			});
		}

		TEST_METHOD(Test_STFBSECURITYDESCRIPTOR)
		{
			test({
				{parserType::FBSECURITYDESCRIPTOR, IDR_SV31FREEBUSYSID1IN, IDR_SV31FREEBUSYSID1OUT},
				{parserType::FBSECURITYDESCRIPTOR, IDR_SV31FREEBUSYSID2IN, IDR_SV31FREEBUSYSID2OUT},
			});
		}

		TEST_METHOD(Test_STXID)
		{
			test({
				{parserType::XID, IDR_SV32XID1IN, IDR_SV32XID1OUT},
				{parserType::XID, IDR_SV32XID2IN, IDR_SV32XID2OUT},
				{parserType::XID, IDR_SV32XID3IN, IDR_SV32XID3OUT},
				{parserType::XID, IDR_SV32XID4IN, IDR_SV32XID4OUT},
			});
		}
	};
} // namespace SmartViewTest